# Generated by Django 5.1.2 on 2024-10-27 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqttApp', '0002_sensorluz_sensorsonido_sensortemp_delete_sensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorluz',
            name='sensor_id',
        ),
        migrations.RemoveField(
            model_name='sensorsonido',
            name='sensor_id',
        ),
        migrations.RemoveField(
            model_name='sensortemp',
            name='sensor_id',
        ),
    ]
