# Generated by Django 5.1.2 on 2024-10-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqttApp', '0003_remove_sensorluz_sensor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alert', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
