# Generated by Django 5.1.2 on 2024-10-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqttApp', '0004_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.IntegerField()),
                ('semaforo', models.CharField(max_length=10)),
            ],
        ),
    ]
