# Generated by Django 5.1.2 on 2024-10-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqttApp', '0006_postura_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
